### ISSUE TITLE
Calling FFNerd.Player.find/2 Crashes in httpoison

### ISSUE THREAD

**Issue by mazz** [jessejanderson/ffnerd-api-elixir#3]
Calling FFNerd.Player.find(name, client) results in a crash in httpoison. 
see https://github.com/mazz/fb_manager_no_otp/blob/master/lib/fb_manager_no_otp.ex#L17
```
iex(1)> pid = FbManagerNoOtp.start_link
#PID<0.187.0>
iex(2)> send(pid, {:add, "Russell Wilson"})
{:add, "Russell Wilson"}
%FFNerd.Client{auth: "hrqevq4h55mt",
 endpoint: "http://www.fantasyfootballnerd.com"}
"Russell Wilson"
** (EXIT from #PID<0.185.0>) evaluator process exited with reason: an exception was raised:
    ** (Poison.SyntaxError) Unexpected end of input
        lib/poison/parser.ex:54: Poison.Parser.parse!/2
        lib/poison.ex:83: Poison.decode!/2
        (ffnerd) lib/ffnerd.ex:27: FFNerd.process_response_body/1
        (httpoison) lib/httpoison/base.ex:413: HTTPoison.Base.response/6
        (ffnerd) lib/ffnerd.ex:2: FFNerd.request!/5
        (ffnerd) lib/ffnerd.ex:10: FFNerd.get/2
        (ffnerd) lib/ffnerd/player.ex:21: FFNerd.Player.list/1
        (ffnerd) lib/ffnerd/player.ex:53: FFNerd.Player.find/2
```

**Comment by mazz** [comment]
The issue is that the endpoint requires `https`
